apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  replicas: 2
  selector:
    matchLabels:
      run: testapp
      version: "1"
  template:
    metadata:
      labels:
        run: testapp
        version: "1"
    spec:
      containers:
        - name: testapp
          image: raduioanciobanu/cloudcomputing:example
          ports:
          - containerPort: 5000
            name: http
            protocol: TCP