apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: db
  name: db
spec:
  containers:
  - image: mobylab/cc-laborator5-db
    name: db
    env:
      - name: POSTGRES_USER
        value: student
      - name: POSTGRES_PASSWORD
        value: student
      - name: POSTGRES_DB
        value: library
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
