apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: procesator
  name: procesator
spec:
  containers:
  - image: mobylab/cc-laborator5-proc
    name: procesator
    env:
      - name: PGHOST
        value: db-cluster-ip-service
      - name: PGDATABASE
        value: library
      - name: PGPORT
        value: "5432"
      - name: PGUSER
        value: student
      - name: PGPASSWORD
        value: student
      - name: AMQPURL
        value: amqp://rabbitmq-cluster-ip-service
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
