apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rabbitmq
  name: rabbitmq
spec:
  containers:
  - image: rabbitmq:3
    name: rabbitmq
    ports:
    - containerPort: 5672
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
